### ISSUE TITLE
Communication between pages and services

### ISSUE THREAD

**Issue by rgaiacs** [CRICDatabase/searchable-image-database-angular#70]
In `src/app/paginas/templates/header/header.component.ts`, we have

```
export class HeaderComponent implements OnInit, OnDestroy {

    @Input() usuarioAutenticado = false;

}
```

The value of `usuarioAutenticado` is changed in by `src/app/services/login/autenticacao.service.ts`

```
                this.usuarioBanco = retorno;
                this.usuarioAutenticado = true;
                this.usuarioLogadoEventEmitter.emit(true);
```

How do I access `usuarioAutenticado` from `src/app/paginas/classificar-imagem/classificar-imagem.component.ts`? Add

```
    @Input() usuarioAutenticado = false;
```

wasn't enough.

**Comment by bernardofagner** [comment]
Quando um usuário faz login no sistema algumas informações sobre ele são registradas no armazenamento da sessao (do browser), o trecho de algoritmo que lida com esse registro está no arquivo 'autenticacao.service.ts', na pasta 'services'. Na linha 51 eu crio um objeto que contém os dados que quero armazenar e salvo estes dados na linha 57. A classe que lida com acessos ao dados armazenados chama-se: 'ArmazenamentoBrowser', e está localizada em: 'utils/browser_storage/browser_storage.ts'. Você pode alterar as propriedades da interface 'IObjetoSessaoModel' para que mapeie quaisquer outras informações que você queira armazenar/recuperar. Esta interface está localizada em: 'models/autenticacao/objeto_sessao.model.ts'.

**Comment by rgaiacs** [comment]
Thanks!
